---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ride-db-credentials
  namespace: ride-hailing-dev
spec:
  encryptedData:
    password: AgBxFFt3RbN+DdsBKR/P9gNsf5GSFPzIqxIiTLLGnehUfu9uuKWxQ4PvMDCHoKBJ8OTCKM13duu8K9SGDSlBySDewj1T1JqOVaaEtof7xL2S8cef3B0B2pkJi3UbeMcqA9Iv4Fe+XbCZhFYY6hUUjbpILlGFR3e1RowgPATKXw+5cvOreJzjCvLjKornEmyWBA3Quz7advPC3COc/ov3saWlKBDhaFptgP6Aq6YUgt6yRm5gnelzGDhYnN9W1r8VJ74iKKQ/FasfwRvVtjxoAxVni54D2Wn1AW9oxYLCyVayUsyPxQ/PwRJ9xLVRZewWSDop6BlMyf9FLirHCmDt2qa9/FLTrsWvbmQT9a019BXCGHpY6LHyLCpzfGLK3uD7jOLPLZl43Iw7k3JtG3hbxBW2ftGr5YteNB+EPrAsbPWEG5yurYQhyiKAtXD4u1byUvzO16zwBeNSMjq6H8N1d+UAJaQurMLe3hWpmibgshmVtkO8IpsmEmowCh2uLJbRwkU4LbG140DSr+wCNjiRJsSnnWwNVP9diRYpnCf4JJ2a8i2Gzu36J0KL/LiSgHK9g/ZhJFlaQQkfcr4sWRO2aC9enBCvyGFVKCrIhj+4JZi3duC/L3GyeMmlPrrmmt/hLmThIglP+H831EkjZ0ESmfBOmPttvNNm64B28qCY4mHBKsCgNXNFGF/Eh9CG9iw7JDsRo7NnuzP5Yw==
    username: AgB69nGB+OHJsIfpsu0Zw4uxOc9qy25C2UlHkalb2PanNhGipEHyvfd+isy3YyDJ5Zal0JThr/Vl7WaUuCPQDlW2LBvl8LFB9Mka7mOLZhTbozQCR6pBZkmsj/JmlipFHfuVp7Xp0iuAhLElyFx0b5NkS+r5jC5EVSf2uetxeUleEqMqMfsbs338ZYEwOoo9oPUHWgaDiUPBa8zmpQy77SmuNR/14Fz9A8R476DR+qHVxkcoFf3OF74afFowHwRkFtSWxmcB0OyQoU2Skb/fP7toOnINT0N27JLGMCoJvgdzDeF0nNgUGgfevdu4gQmQKPXHe3UJOqAZj00nuUen5ilsJSFa2reFHuKjtWXBdhLsYGimXuDsCOfKwDmQjaskvyONJDQ+euP+RrkixE9YwhpeTUJIJ+kfGwCGYgGpzFBt/9ODA4e4TMQd2rsLp+8C9NdBLsSSZl53VpYq4aygHJmQKzxUipjobe1ktqqOQQpX7/+L4NXwlnR+0XswYEUKbimuk0Gr5xaDlONbfp33h0MWDZW9FYItyu1Yudk+c4pYyAVpzDHUvRUZhNFBR2ndETe9VDjaP/wb44jeFKsMbIhH3Syzjbdna5uXOo9sDS6g/iGmWTL2bEgC8ILosANfepY5uSJX0PQnG3Iesel5KYZX8h5AEhjWrJ7cV450Bd6iiSg8POqNU6BaTsa/+7u/jcdiw9iS0248wg==
  template:
    metadata:
      name: ride-db-credentials
      namespace: ride-hailing-dev
    type: Opaque
