---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ride-db-credentials
  namespace: ride-hailing-dev
spec:
  encryptedData:
    password: AgATYrZ2VwVOIncdOAYJR7JrdQDwIoBd6ya1j+CveyyC1iRQFKTEv/yKJKehHdvDmaALHLiHxod3XozygJuek4uXnTUVPePHz3Um4wHBnE7dlCzF3wuxIw2nAxvUNqY2OJnyoOUHAzdo+DWIiYbIBdyuFHVC+KPZHEM0ZHXFAbAO5so9toxvDD0eft3byQ9jqBoTKyj1PelI8l6qbnUEwell9KlIP/vEX5HS4yrqLyI9E9R1b8i+5eXw9fvti41reU4NpFb4P7xgrKm5sBVAeuxnjmAGI+bK+Oxg1upeN2ohnZkChWeSf8Sv+q14SiOLXKgWmeJHAPpECnSk3aZaDlXupgGjMEboTF0rugoqp5LKVLpYhYDMXzLNZFKYLS0JQGREvPBY2e2aOt1thRphKS2OlZvKMhepa0CH2GcAU1UNlKEXTFGW6BOVinv2vcF9vgcwTv9hXrIGd/obDka7cICCeRzhIFcQlrIIrAWbqbwk4/yfeRTKnTGDns5//5VX0iXN6rHq4sYMK0xi4X+mpETJi5nw+tEe91Ft1E8QZDSREchJuiLsmPo2ePEy8pUjvTVUiODjRhCsBxUZclRWkOPG2rQPO4cK+OqqixfhMnmhstqOXIcePZN1SFL8AuMm4Yks0LTFoFSYIyfv3f0Nndj8e06c53o/Nfl4qiqfx2viTZBDPM2vmV/qZI4CkLj0RvVMqTzzu5fqpw==
    username: AgAoGZu9eT0eVNdl+Ecc3Cs9Eo5I9ejSi0+3GgPep6jQYGcqq0VNW85StBh+zdzvxafOOPjzXcjW/yQV/2v94EwWl+TMswJZ8jwnVpQt2uacRmzGJbbxYIVN09tXkAfSVis+UGQnWkNkNDL3e77j0B1XLRy78OhBPFbIKgP4pflw2pspGEh7FRTcRVNIF/rsiBYcuudMzBScJcKCtT8u4G1heno9yMmWABoXLG/Uv/eSUtmzpEoGTUDdAAuVWG+XBRcb8nNO2+uX1+mbhBHku4cUVc42o0HnvymDDnvXWB+tIBw3cYshVPG1oDltnADcHMzmbtIpckIbnLmVAI1qLLB/LCBYgzsrPT47TChCXe4vLzSHAuLqLGhNl4kdFZCvsGsidhk0Twpv2GwRr6Qr9w8GYMze/rDqFtandCubf2DDauSJMgl+5MFfe0Y2llBRRNxM2SLhGUIOxNbkZs55B7DqyGSJQMUN15yF21iW/a2pDLvOMRc30VtJf2LL00k02c5meeAd5dioy01No6ndMxzaBpNNx0g3dLJkUrBTES1C58IHHjgBUN/p5xzoXGKcDBZq0FquIJ3hRfwDt9N+0zN44JNUSiJMXimv9kWGM/bOd3+7mSePcg4gAdjm1BH2t7vOVtcy79LYjlH5HDu7SPElqSnbV5ASDl+f0Ws4pyoyZ0Qod5wO32Bm6tDN9g0uqgkvRvYrB0jMmQ==
  template:
    metadata:
      name: ride-db-credentials
      namespace: ride-hailing-dev
    type: Opaque
