---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ride-db-credentials
  namespace: ride-hailing-dev
spec:
  encryptedData:
    password: AgA6mOjg5jfPsww5xNnW2Wn2XZeg+DmeuYgN/HPGY1nNZSrjCrbol7LZxSoeWQnVz2oL7hbPEbuueVnEaWAIzTv+v2gbjUm4x0xEzUJ9Cn4WwyOVzYk9fhtM0zfjFB+w+ZkiYyjbrudMG1vTd8KBsZNo3mbqK4vhYhBeUV078vXIkJogm7PVzJjxFo4pYYlzet/dvo1PU9dymTCpnVaHmtn2XBWWGpLsYlUkA+ulf5uuvNXPfYgrQl+YH/CC71OBpCtNzsgRs4YXzTmkw27kUwWfaqbH/J1upo4bFFDlKPtND40p5DVaJZ0Pn8D9eJn4qjoeoSd8KGgYr5el88mKlNEw1AD0Zsw5ASZtQwZamdhe6ehiMRx6MX3OuXYMm6BkHZ0dl/4z96XEFE16PqvIiJbOB+VleTyoY7us6OvbJsZ7L/JetcjcpYpASh4rNx/BLk3exCrAwB23VovawWh0wdyZDF/F8RX7+bfPnyq+dmHlmwZ/bd5as+5xbbSuHc1W595R537hiusPu4New51BB+y7D4FcNADNrkj5QUusCbu0zp1gk6A42RAHWHizYa7QfWARiIDypiyvvTP2ThFRI5r25Xv2y7U6a+WILYJKg5UobssMTM/kdILpp6SOAoyzP8oP+L0XUz8jEUtQFNCvmiEMAmDcLbbxoZHg2nMDLGw0v2tVQA2xivnw2/SG0GaySKweb8tHsa6+OQ==
    username: AgAHI0TRVQ8B4P13vvPwlGODGBJ2XZhEyKfQ5rOm4RBDPx1NaOqWXNHBhWFm6ebz8H1m5/ChDEZiaJAjL/UUnFPqI1tDzIfeOoh6hvIT5yYQAsmp3URKPvBSAuzayjKE0zL8L4lOzyiihP0VQ4s8+ykPGQdJTlvCCCX3bah4MFKXPptZAEXlxhFFyjGQOEvi7AjhsWSKdR3NaWYs/Q7WFevhVdS8E5N/Hh0lND3X4JYCj3ovjU8suAWbN4vd2+Lym4CeHjW4+KTJN58gN9h0aKDJdB5sb9IR709y1Fy/sMpy9zP0/LfT09PpcauzY/gyk8XmR5HFrcO8N1oPHQd4JErddFYvAYfRxX9OMP6MRnVLICZks6smcyG1Ng8wZV78BOkPDdLd7nQEupZgrBzHhij/fMXyrdpxp7QUAlcoNfNjmoyal0HzcTxX8vNFFoVciXchiSNc8fvwbi4cv+oSWfYicDZ8pJ3J9nXhbpTVIvju5vJXdQCAK5SOD9Ye/b05/9YTwnhViRxzdFWJK3FaEmU7abbSNfe4Q641zIyPGKLsC7mIykf2uNlP4pygmnunfz1BZ1tBVVBOKBFQMeOR7O7BSI8kN90yauSjWe3JK4mwbcBC7wYQdLZeNt3i2ZZzh4NyINPw8uMtEne6CSdEOX+eIpHEtOAXz6mZvKbfmolJ6AkLXI8khAhwn2v57k+0O+4NOTURoRBivA==
  template:
    metadata:
      name: ride-db-credentials
      namespace: ride-hailing-dev
    type: Opaque
