architecture: standalone
auth:
  enabled: false
image:
  registry: docker.io
  repository: bitnamilegacy/redis
  tag: 8.2.1-debian-12-r0
persistence:
  enabled: false
master:
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 100m
      memory: 128Mi
