apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: ride-hail-platform
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 18.*
      helm:
        releaseName: redis
        parameters:
          - name: image.registry
            value: docker.io
          - name: image.repository
            value: bitnamilegacy/redis
          - name: image.tag
            value: 8.2.1-debian-12-r0
        valueFiles:
          - $values/platform/redis/values.yaml
    - repoURL: '{{ .Values.repoURL }}'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
