apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- k8s.yaml
- istio.yaml

commonLabels:
  app: ride-service
  version: v1
  managed-by: argocd

images:
- name: docker.io/ama2352/ride-service
  newName: docker.io/ama2352/ride-service
  newTag: latest
