apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rsa-keys
spec:
  encryptedData:
    private.pem: REPLACE_WITH_KUBESEAL_ENCRYPTED_PRIVATE_PEM_FOR_DEV
    public.pem: REPLACE_WITH_KUBESEAL_ENCRYPTED_PUBLIC_PEM_FOR_DEV
  template:
    metadata:
      name: rsa-keys
    type: Opaque
