apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ride-hailing-dev

resources:
  - ../../base
  - sealed-secrets/rsa-keys.yaml

images:
  - name: docker.io/ama2352/user-service
    newTag: "48-20a5f650"
